version: "3.7"

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    container_name: rails_api

    build:
      context: .

      dockerfile: config/containers/app/Dockerfile

    depends_on:
      - db
    ports:
      - '3001:3000'

    volumes:
      - .:/var/www/app

    labels:
      com.datadoghq.ad.logs: '[{"source": "ruby", "service": "app"}]'

    environment:
      PG_PASSWORD: password
      DATADOG_HOST: datadog

  # agent section
  datadog:
    image: "datadog/agent:latest"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_LOGS_ENABLED=true
      - DD_AC_INCLUDE="name:rails_api" 
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_SITE=datadoghq.eu

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro